name: Build & Release APK

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      - name: Set Signing Environment Variables
        run: |
          echo "KEYSTORE_PATH=$GITHUB_WORKSPACE/release.keystore" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Give Gradle Execute Permission
        run: chmod +x ./gradlew

      - name: Build Signed Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK to car-music.apk
        run: |
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/car-music.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: car-music.apk
          path: app/build/outputs/apk/release/car-music.apk

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: app/build/outputs/apk/release/car-music.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
